# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Kavita
version: "latest"
slug: kavita
description: "A self-hosted digital library for comics and eBooks."
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
ports:
  5000/tcp: 5000
map:
  - type: addon_config
    read_only: False
  - type: share
    read_only: False
    path: /share/kavita
usb: true
options:
  kavita_port: 5000
schema:
  kavita_port: int(1024,65535)
image: "ghcr.io/kareadita/kavita"
